import { motion as m } from "framer-motion";
import { FaLaptop, FaExclamationTriangle, FaIdCard, FaUserPlus, FaEnvelopeOpenText, FaSignInAlt, FaDownload } from "react-icons/fa";
import { fadeIn } from "../../components/transitions";
import { useNavigate } from "react-router-dom";
import { useEffect } from "react";

// --- Data: Steps Configuration ---
const stepsData = [
  {
    id: "01",
    title: "Select Membership Type",
    icon: <FaIdCard />,
    description: "Choose the appropriate membership level. This will redirect you to the official ACM payment portal.",
    actions: [
      {
        label: "Student Membership",
        link: "https://services.acm.org/public/qj/proflevel/proflevel_control.cfm?level=3&country=India&form_type=Student&promo=ACMMSDEPT&pay=DD",
        primary: true
      },
      {
        label: "Professional Membership",
        link: "https://services.acm.org/public/qj/proflevel/proflevel_control.cfm?level=3&country=India&form_type=Professional&promo=LEVEL&pay=DD",
        primary: false
      }
    ]
  },
  {
    id: "02",
    title: "Create ACM Account",
    icon: <FaUserPlus />,
    description: "After payment, create your web account. You must use the exact same email address provided during payment to link your membership correctly.",
    actions: [
      {
        label: "Create Web Account",
        link: "https://accounts.acm.org/signin.cfm",
        primary: false
      }
    ]
  },
  {
    id: "03",
    title: "Email Verification",
    icon: <FaEnvelopeOpenText />,
    description: "Check your inbox for a verification email. Click the link provided. Do not modify the URL in your browser address bar.",
    actions: []
  },
  {
    id: "04",
    title: "Login to MyACM",
    icon: <FaSignInAlt />,
    description: "Log in using the Username autogenerated by ACM (this will be sent to your email) or your verified email address.",
    actions: [
      {
        label: "Login Portal",
        link: "https://myacm.acm.org/",
        primary: false
      }
    ]
  },
  {
    id: "05",
    title: "Download Card",
    icon: <FaDownload />,
    description: "Navigate to your dashboard to download your PDF card. If it is not immediately visible, access the direct dashboard link below.",
    actions: [
      {
        label: "Access Dashboard",
        link: "https://myacm.acm.org/dashboard.cfm?svc=services",
        primary: true
      }
    ]
  }
];

const Membership = () => {
  const navigate = useNavigate();

  useEffect(() => {
    console.log("✅ Admin shortcut (Ctrl + Shift + G) attached");

    const handleKeyDown = (e: KeyboardEvent) => {
      if (
        e.ctrlKey &&
        e.shiftKey &&
        e.key.toLowerCase() === "g"
      ) {
        e.preventDefault();
        navigate("/admin/login");
      }
    };

    window.addEventListener("keydown", handleKeyDown);

    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [navigate]);

  return (
    <>
      <div className='membership-page'>

        {/* --- Header Section --- */}
        <div className="membership-header">
          <m.div
            variants={fadeIn("down", 0)}
            initial="hidden"
            animate="show"
          >
            <div className="device-badge">
              <FaLaptop /> Desktop Recommended
            </div>
          </m.div>

          <m.h1
            variants={fadeIn("up", 0)}
            initial="hidden"
            animate="show"
            className="main-title"
            viewport={{ once: false, amount: 0.7 }}
          >
            ACM <span className="highlight-text">Membership Guide</span>
          </m.h1>

          <m.p
            variants={fadeIn("up", 0.25)}
            initial="hidden"
            animate="show"
            className="sub-title"
          >
            Follow this step-by-step roadmap to secure your membership and access your digital card.
          </m.p>
        </div>

        {/* --- Alert Box --- */}
        <m.div
          className="alert-box"
          variants={fadeIn("up", 0.35)}
          initial="hidden"
          animate="show"
        >
          <div className="alert-icon"><FaExclamationTriangle /></div>
          <div className="alert-content">
            <h3>Critical Requirements</h3>
            <ul>
              <li><strong>Do not create an account</strong> before paying for the membership.</li>
              <li><strong>Verify your email</strong> spelling carefully. Use an active, accessible email address.</li>
            </ul>
          </div>
        </m.div>

        {/* --- Stacked Steps Container --- */}
        <m.div
          className="steps-container"
          initial="hidden"
          animate="show"
        >
          {stepsData.map((step, index) => (
            <m.div
              key={step.id}
              className="step-card"
              variants={fadeIn("up", 0.15 + index * 0.1)}
            >
              {/* Left Column: Number & Icon */}
              <div className="card-left">
                <div className="step-number-badge">{step.id}</div>
                <div className="step-icon-wrapper">
                  {step.icon}
                </div>
              </div>

              {/* Right Column: Content */}
              <div className="card-content">
                <h2>{step.title}</h2>
                <p>{step.description}</p>

                {step.actions.length > 0 && (
                  <div className="action-row">
                    {step.actions.map((action, idx) => (
                      <a
                        key={idx}
                        href={action.link}
                        target="_blank"
                        rel="noopener noreferrer"
                        className={`glass-btn ${action.primary ? 'primary' : 'secondary'}`}
                      >
                        {action.label}
                      </a>
                    ))}
                  </div>
                )}
              </div>
            </m.div>
          ))}
        </m.div>

        {/* --- Footer --- */}
        <m.footer
          className="support-footer"
          variants={fadeIn("up", 0.4)}
          initial="hidden"
          animate="show"
        >
          <p>Experiencing technical difficulties?</p>
          <a
            href="mailto:acmindiahelp@hq.acm.org"
            className="support-link"
          >
            Contact ACM Help Desk →
          </a>
        </m.footer>
      </div>
    </>
  );
};

export default Membership;