import { motion as m } from "framer-motion";
import { FaLaptop, FaExclamationTriangle, FaIdCard, FaUserPlus, FaEnvelopeOpenText, FaSignInAlt, FaDownload } from "react-icons/fa";
import { fadeIn } from "../../components/transitions";
import { useNavigate } from "react-router-dom";
import { useEffect } from "react";

// --- Data: Steps Configuration ---
const stepsData = [
  {
    id: "01",
    title: "Select Membership Type",
    icon: <FaIdCard />,
    description: "Choose the appropriate membership level. This will redirect you to the official ACM payment portal.",
    actions: [
      {
        label: "Student Membership",
        link: "https://services.acm.org/public/qj/proflevel/proflevel_control.cfm?level=3&country=India&form_type=Student&promo=ACMMSDEPT&pay=DD",
        primary: true
      },
      {
        label: "Professional Membership",
        link: "https://services.acm.org/public/qj/proflevel/proflevel_control.cfm?level=3&country=India&form_type=Professional&promo=LEVEL&pay=DD",
        primary: false
      }
    ]
  },
  {
    id: "02",
    title: "Create ACM Account",
    icon: <FaUserPlus />,
    description: "After payment, create your web account. You must use the exact same email address provided during payment to link your membership correctly.",
    actions: [
      {
        label: "Create Web Account",
        link: "https://accounts.acm.org/signin.cfm",
        primary: false
      }
    ]
  },
  {
    id: "03",
    title: "Email Verification",
    icon: <FaEnvelopeOpenText />,
    description: "Check your inbox for a verification email. Click the link provided. Do not modify the URL in your browser address bar.",
    actions: []
  },
  {
    id: "04",
    title: "Login to MyACM",
    icon: <FaSignInAlt />,
    description: "Log in using the Username autogenerated by ACM (this will be sent to your email) or your verified email address.",
    actions: [
      {
        label: "Login Portal",
        link: "https://myacm.acm.org/",
        primary: false
      }
    ]
  },
  {
    id: "05",
    title: "Download Card",
    icon: <FaDownload />,
    description: "Navigate to your dashboard to download your PDF card. If it is not immediately visible, access the direct dashboard link below.",
    actions: [
      {
        label: "Access Dashboard",
        link: "https://myacm.acm.org/dashboard.cfm?svc=services",
        primary: true
      }
    ]
  }
];

// --- CSS Styles ---
const styles = `
  :root {
    --primary-blue: #3b82f6;
    --primary-glow: rgba(59, 130, 246, 0.4);
    --warning: #f59e0b;
  }

  .membership-page {
    width: 100%;
    padding: 120px 5% 100px;
    font-family: 'Poppins', sans-serif;
    overflow-x: hidden;
    background: transparent;
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  /* --- Header --- */
  .membership-header {
    text-align: center;
    margin-bottom: 50px;
    max-width: 800px;
  }

  .main-title {
    font-size: 3.5rem;
    font-weight: 800;
    line-height: 1.1;
    color: #fff;
    margin-bottom: 20px;
    text-shadow: 0 0 20px rgba(0,0,0,0.5);
  }
  
  .highlight-text {
    background: linear-gradient(120deg, #fff, var(--primary-blue));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    filter: drop-shadow(0 0 10px var(--primary-glow));
  }

  .sub-title {
    color: #cbd5e1;
    font-size: 1.1rem;
    line-height: 1.6;
  }

  .device-badge {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 6px 16px;
    background: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 50px;
    color: #94a3b8;
    font-size: 0.85rem;
    margin-bottom: 20px;
  }

  /* --- Alert Box --- */
  .alert-box {
    width: 100%;
    max-width: 850px;
    margin-bottom: 60px;
    background: rgba(245, 158, 11, 0.05);
    border: 1px solid rgba(245, 158, 11, 0.3);
    backdrop-filter: blur(10px);
    border-radius: 16px;
    padding: 24px;
    display: flex;
    gap: 20px;
    align-items: flex-start;
    box-shadow: 0 0 30px rgba(245, 158, 11, 0.05);
  }

  .alert-icon {
    font-size: 1.8rem;
    color: var(--warning);
    margin-top: 2px;
  }

  .alert-content h3 {
    color: var(--warning);
    margin: 0 0 8px 0;
    font-size: 1.1rem;
    text-transform: uppercase;
    letter-spacing: 1px;
    font-weight: 700;
  }

  .alert-content ul {
    margin: 0;
    padding-left: 20px;
    color: #e2e8f0;
    font-size: 0.95rem;
    line-height: 1.6;
  }

  /* --- Steps Container --- */
  .steps-container {
    width: 100%;
    max-width: 850px;
    display: flex;
    flex-direction: column;
    gap: 25px;
  }

  /* --- Step Card (Glassmorphism) --- */
  .step-card {
    padding: 35px;
    background: rgba(255, 255, 255, 0.03); 
    backdrop-filter: blur(12px);
    -webkit-backdrop-filter: blur(12px);
    border-radius: 20px;
    border: 1px solid rgba(255, 255, 255, 0.08);
    box-shadow: 0 4px 30px rgba(0, 0, 0, 0.2);
    transition: all 0.3s ease;
    position: relative;
    overflow: hidden;
    display: flex;
    gap: 30px;
  }

  .step-card:hover {
    transform: translateY(-5px);
    background: rgba(255, 255, 255, 0.06);
    border-color: rgba(59, 130, 246, 0.3);
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.4);
  }

  /* Left Side: Number & Icon */
  .card-left {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 15px;
    min-width: 60px;
  }

  .step-number-badge {
    font-size: 1.8rem;
    font-weight: 800;
    color: rgba(255,255,255,0.1);
    line-height: 1;
  }

  .step-icon-wrapper {
    width: 50px;
    height: 50px;
    border-radius: 12px;
    background: rgba(59, 130, 246, 0.1);
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--primary-blue);
    font-size: 1.4rem;
    border: 1px solid rgba(59, 130, 246, 0.2);
    box-shadow: 0 0 15px rgba(59, 130, 246, 0.1);
  }

  .step-card:hover .step-icon-wrapper {
    background: var(--primary-blue);
    color: #fff;
    box-shadow: 0 0 20px var(--primary-glow);
  }

  /* Right Side: Content */
  .card-content {
    flex: 1;
  }

  .card-content h2 {
    margin: 0 0 10px 0;
    color: #fff;
    font-size: 1.5rem;
    font-weight: 700;
  }

  .card-content p {
    color: #cbd5e1;
    line-height: 1.6;
    margin-bottom: 20px;
    font-size: 0.95rem;
  }

  /* --- Buttons --- */
  .action-row {
    display: flex;
    gap: 12px;
    flex-wrap: wrap;
  }

  .glass-btn {
    padding: 10px 24px;
    border-radius: 8px;
    font-weight: 600;
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    text-decoration: none;
    transition: all 0.3s ease;
    cursor: pointer;
    border: 1px solid rgba(59, 130, 246, 0.5);
    display: inline-flex;
    align-items: center;
    justify-content: center;
  }

  .glass-btn.primary {
    background: rgba(59, 130, 246, 0.15);
    color: #60a5fa;
  }
  .glass-btn.primary:hover {
    background: var(--primary-blue);
    color: white;
    box-shadow: 0 0 20px rgba(59, 130, 246, 0.4);
  }

  .glass-btn.secondary {
    background: transparent;
    border-color: rgba(255, 255, 255, 0.2);
    color: #cbd5e1;
  }
  .glass-btn.secondary:hover {
    border-color: #fff;
    color: #fff;
    background: rgba(255, 255, 255, 0.05);
  }

  /* --- Footer --- */
  .support-footer {
    text-align: center;
    margin-top: 80px;
    padding-top: 30px;
    border-top: 1px solid rgba(255,255,255,0.1);
    width: 100%;
    max-width: 850px;
  }
  .support-footer p { color: #94a3b8; }
  .support-link { color: var(--primary-blue); text-decoration: none; font-weight: 600; }

  /* ---------------- Responsive ---------------- */
  @media screen and (max-width: 768px) {
    .membership-page { padding: 100px 20px; }
    .main-title { font-size: 2.5rem; }
    
    .step-card {
      flex-direction: column;
      gap: 15px;
      padding: 25px;
    }

    .card-left {
      flex-direction: row;
      width: 100%;
      justify-content: space-between;
    }

    .step-icon-wrapper {
      width: 40px; height: 40px; font-size: 1.1rem;
    }
  }
`;

const Membership = () => {
  const navigate = useNavigate();

  useEffect(() => {
    console.log("✅ Admin shortcut (Ctrl + Shift + G) attached");

    const handleKeyDown = (e: KeyboardEvent) => {
      if (
        e.ctrlKey &&
        e.shiftKey &&
        e.key.toLowerCase() === "g"
      ) {
        e.preventDefault();
        navigate("/admin/login");
      }
    };

    window.addEventListener("keydown", handleKeyDown);

    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [navigate]);

  return (
    <>
      <style>{styles}</style>

      <div className='membership-page'>

        {/* --- Header Section --- */}
        <div className="membership-header">
          <m.div
            variants={fadeIn("down", 0)}
            initial="hidden"
            animate="show"
          >
            <div className="device-badge">
              <FaLaptop /> Desktop Recommended
            </div>
          </m.div>

          <m.h1
            variants={fadeIn("up", 0)}
            initial="hidden"
            animate="show"
            className="main-title"
            viewport={{ once: false, amount: 0.7 }}
          >
            ACM <span className="highlight-text">Membership Guide</span>
          </m.h1>

          <m.p
            variants={fadeIn("up", 0.25)}
            initial="hidden"
            animate="show"
            className="sub-title"
          >
            Follow this step-by-step roadmap to secure your membership and access your digital card.
          </m.p>
        </div>

        {/* --- Alert Box --- */}
        <m.div
          className="alert-box"
          variants={fadeIn("up", 0.35)}
          initial="hidden"
          animate="show"
        >
          <div className="alert-icon"><FaExclamationTriangle /></div>
          <div className="alert-content">
            <h3>Critical Requirements</h3>
            <ul>
              <li><strong>Do not create an account</strong> before paying for the membership.</li>
              <li><strong>Verify your email</strong> spelling carefully. Use an active, accessible email address.</li>
            </ul>
          </div>
        </m.div>

        {/* --- Stacked Steps Container --- */}
        <m.div
          className="steps-container"
          initial="hidden"
          animate="show"
        >
          {stepsData.map((step, index) => (
            <m.div
              key={step.id}
              className="step-card"
              variants={fadeIn("up", 0.15 + index * 0.1)}
            >
              {/* Left Column: Number & Icon */}
              <div className="card-left">
                <div className="step-number-badge">{step.id}</div>
                <div className="step-icon-wrapper">
                  {step.icon}
                </div>
              </div>

              {/* Right Column: Content */}
              <div className="card-content">
                <h2>{step.title}</h2>
                <p>{step.description}</p>

                {step.actions.length > 0 && (
                  <div className="action-row">
                    {step.actions.map((action, idx) => (
                      <a
                        key={idx}
                        href={action.link}
                        target="_blank"
                        rel="noopener noreferrer"
                        className={`glass-btn ${action.primary ? 'primary' : 'secondary'}`}
                      >
                        {action.label}
                      </a>
                    ))}
                  </div>
                )}
              </div>
            </m.div>
          ))}
        </m.div>

        {/* --- Footer --- */}
        <m.footer
          className="support-footer"
          variants={fadeIn("up", 0.4)}
          initial="hidden"
          animate="show"
        >
          <p>Experiencing technical difficulties?</p>
          <a
            href="mailto:acmindiahelp@hq.acm.org"
            className="support-link"
          >
            Contact ACM Help Desk →
          </a>
        </m.footer>
      </div>
    </>
  );
};

export default Membership;